[package]
name = "tokio-pty-command"
version = "0.1.0"
authors = [ "NAKASHIMA, Makoto <makoto.nksm+github@gmail.com>" ]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = "0.6.22"
nix = "0.18.0"
tokio = { version = "0.2.22", features = [ "process" ] }
